/* auto-generated by OHOS-RS */
/* eslint-disable */


export declare function registerArktsCallback(callback: (arg: string) => void): void

export declare function setInterceptorState(state: boolean): boolean

export declare function markImport(): void

export declare function markImportRespack(): void

export declare function setChosenFile(file: string): void

export declare function setInputText(text: string): void

