/* auto-generated by OHOS-RS */
/* eslint-disable */

export interface InputBoxRequest {
  /** Raw pointer to the callback. Pass this value back unchanged in the response. */
  callback: number
  title: string
  prompt?: string
  defaultValue: string
  mode: string
  okLabel: string
  cancelLabel: string
  width?: number
  height?: number
  autoWrap: boolean
  scrollToEnd: boolean
}

export interface InputBoxResponse {
  /** Raw pointer to the callback. Must be the same value from the request. */
  callback: number
  text?: string
  error?: string
}

/**
 * Handle response from ArkTS layer.
 *
 * This function should be called from ArkTS when the user completes or cancels
 * the input dialog.
 *
 * # Safety
 *
 * The `callback` field in the response must be the exact same value received
 * in the corresponding [`InputBoxRequest`]. Passing any other value will cause
 * undefined behavior.
 *
 * # Example
 *
 * ```typescript
 * import inputbox from 'libinputbox.so';
 *
 * // When user clicks OK:
 * inputbox.onInputboxResponse({
 *   callback: request.callback,
 *   text: userInputText,
 *   error: null
 * });
 *
 * // When user clicks Cancel:
 * inputbox.onInputboxResponse({
 *   callback: request.callback,
 *   text: null,
 *   error: null
 * });
 * ```
 */
export declare function onInputboxResponse(response: InputBoxResponse): void

/**
 * Register the ArkTS callback handler for input box requests.
 *
 * This function must be called from ArkTS before using the InputBox API.
 * The callback will receive [`InputBoxRequest`] objects when `show()` is called.
 *
 * # Example
 *
 * ```typescript
 * import inputbox from 'libinputbox.so';
 *
 * inputbox.registerInputboxCallback((request) => {
 *   // Display dialog and handle user input
 * });
 * ```
 */
export declare function registerInputboxCallback(callback: (arg: InputBoxRequest) => void): void

export declare function registerArktsCallback(callback: (arg: string) => void): void

export declare function setInterceptorState(state: boolean): boolean

export declare function markImport(): void

export declare function markImportRespack(): void

export declare function processExportFdOhos(fd: number): void

export declare function setChosenFile(file: string): void

export declare function setInputText(text: string): void

