/* auto-generated by OHOS-RS */
/* eslint-disable */
//miniquad
export declare function reRegisterEventFilters(): boolean

export declare function registerArktsCallback(callback: (arg: string) => void): void

export declare function registerEventFilters(windowId: number): boolean

export declare function unregisterEventFilters(): boolean

//phira
export declare function markImport(): void

export declare function markImportRespack(): void

export declare function setChosenFile(file: string): void

export declare function setInputText(text: string): void

